# Generated by Django 5.1.7 on 2025-06-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='username',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
